### ISSUE TITLE
Test fail when building from scratch on Ubuntu

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#24]
I tried to build from scratch in a VirtualBox. The make command completed without errors, but make test resulted in four failed tests:
[MakeTest-log.txt](https://github.com/GridOPTICS/GridPACK/files/2412405/MakeTest-log.txt)

- 	 41 - complex_dae_solver_parallel (Timeout)
- 	 43 - real_dae_solver_parallel (Timeout)
- 	 65 - dynamic_simulation_full_y_parallel (Timeout)
- 	 71 - kalman_ds_parallel (Failed)

I attached a log of the screen output.

**Comment by wperkins** [comment]
The Timeout problems could probably be fixed by increasing the test timeout.  The [instructions](https://www.gridpack.org/wiki/index.php/Building_on_Ubuntu) had 
```
-D GRIDPACK_TEST_TIMEOUT:STRING=20
```
in the GridPACK configuration on that [page](https://www.gridpack.org/wiki/index.php/Building_on_Ubuntu). This works in _my_ Ubuntu VM, but perhaps I have a better host machine.  I increased it to 60 on that page, but I doubt there is a good value that would work for _all_ VM configurations.

**Comment by bjpalmer** [comment]
I'll try this in my Ubuntu virtual machine and see if I get the same failure for Kalman DS. I think we should increase the default timeout to 120 seconds (in GridPACK.cmake) and see if we can get most of the timeout errors to disappear. Will still probably have a few regular expression errors, but there doesn't seem to be much that can be done about those, other than documenting them in the build instructions.

**Comment by tobyjunker** [comment]
Makes sense. So once the instructions are updated accordingly (time out and reg ex) we can close this ticket.

**Comment by bjpalmer** [comment]
I updated the documentation on the build from scratch for Ubuntu. I probably am not going to get a chance to find out what the problem with the Kalman filter is any time soon. Was this a regular expression failure or something more sever? You can run this test standalone by going down into the build/applications/kalman_ds directory and typing

mpirun -n 2 kds.x input_14.xml

Does the test appear to run?

**Comment by tobyjunker** [comment]
This Issue should not have been closed yet. Timeout and Kalman filter errors still need to be addressed. See Issues #40 and #41, respectively.
